version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: baas_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: baas_db
      MYSQL_USER: samirdourado
      MYSQL_PASSWORD: baas_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: